obj-y			+= drm/ vga/ stub/ ion/

ifeq ($(CONFIG_MSM_KGSL_ADRENO200),y)
    obj-y += msm_adreno200/
endif

ifeq ($(CONFIG_MSM_KGSL_ADRENO205),y)
    obj-y += msm_adreno205/
endif

ifeq ($(CONFIG_MSM_KGSL_ADRENO220),y)
    obj-y += msm_adreno220/
endif

ifeq ($(CONFIG_MSM_KGSL_ADRENO225),y)
    obj-y += msm/
endif
