
obj-$(CONFIG_USB_FUNCTION_MSM_HSUSB)	+= msm_hsusb.o
obj-$(CONFIG_USB_FUNCTION_NULL)		+= null.o
obj-$(CONFIG_USB_FUNCTION_NULL)		+= zero.o
obj-$(CONFIG_USB_FUNCTION_LOOPBACK)	+= loopback.o
obj-$(CONFIG_USB_FUNCTION_ADB)		+= adb.o
obj-$(CONFIG_USB_FUNCTION_UMS)		+= ums.o
obj-$(CONFIG_USB_FUNCTION_MASS_STORAGE)		+= mass_storage.o
obj-$(CONFIG_USB_FUNCTION_DIAG)		+= diag.o
obj-$(CONFIG_USB_FUNCTION_ETHER)	+= ether.o
obj-$(CONFIG_USB_FUNCTION_SERIAL)	+= fserial.o
obj-$(CONFIG_USB_FUNCTION_MODEM)	+= serial.o
obj-$(CONFIG_USB_FUNCTION_FSYNC)	+= fsync.o
obj-$(CONFIG_USB_FUNCTION_PROJECTOR)	+= projector.o
obj-$(CONFIG_USB_FUNCTION_RNDIS)        += rndis.o
obj-$(CONFIG_USB_FUNCTION_MTP_TUNNEL)   += mtp_tunnel.o
