#
# Makefile for the opticaljoystick drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_OPTICALJOYSTICK_CRUCIAL_uP)	+= curcial.o
obj-$(CONFIG_OPTICALJOYSTICK_CRUCIAL_SPI)	+= curcial_spi.o
