
obj-$(CONFIG_WIMAX_I2400M)	+= i2400m/
obj-$(CONFIG_WIMAX_SQN)		+= SQN/
obj-$(CONFIG_WIMAX_SQN)		+= wimaxdbg/
obj-$(CONFIG_WIMAX_SQN)		+= wimaxuart/

# (from Sam Ravnborg) force kbuild to create built-in.o
obj- := dummy.o
